workspace(nix): initial docker image
gitpod-io/workspace-images pull request #438
Opened 2021-07-06 11:28 UTC by ghuntley

2021-08-09 09:50 UTC, jankeromnes requested changes
Hey, super cool! Many thanks for this. 🙏

Please simply hook up the job (see below) so that CircleCI can build it. Then we'll know if the build passes or not, and we'll be able to test the resulting Docker image.

2021-08-09 09:50 UTC, jankeromnes commented on .circleci/config.yml
> +  workspace-nix:
Please also register this new job in the list at the bottom of this file (in order to make CircleCI actually run it). 🙏

2021-09-17 20:59 UTC, shism2 commented
Just attaching as a reference if anyone finds it useful

`FROM buildpack-deps:focal-curl

COPY  install-packages /usr/bin

ARG DEBIAN_FRONTEND=noninteractive
ARG DUSER=gitpod
ENV HOME=/home/$DUSER

RUN install-packages \
        bash-completion \
        sudo \
        xz-utils \
        git \
# '-l': see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
&&  useradd -l -u 33333 -G sudo -md $HOME -s /bin/bash -p $DUSER $DUSER \
# passwordless sudo for users in the 'sudo' group
&& echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && mkdir -m 0755 /etc/nix &&  chown $DUSER /etc/nix

CMD /bin/bash -l
USER $DUSER
ENV USER $DUSER
WORKDIR $HOME

RUN  touch .bash_profile && curl https://nixos.org/releases/nix/nix-2.3.15/install | sh \
&& echo '. $HOME/.nix-profile/etc/profile.d/nix.sh' >> $HOME/.bashrc \
&& mkdir -p  ~/.config/nix/ &&  printf "sandbox = false\nexperimental-features = nix-command flakes\nkeep-derivations = true\nkeep-outputs = true" > ~/.config/nix/nix.conf \
&& mkdir -p  $HOME/.config/nixpkgs && echo '{ allowUnfree = true; }' >> $HOME/.config/nixpkgs/config.nix

RUN . $HOME/.nix-profile/etc/profile.d/nix.sh \
&& nix-channel --add https://nixos.org/channels/nixpkgs-unstable  \
&& nix-channel --update \
&& nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager \
&& nix-channel --update \
&& export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH \
&& echo 'export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH' >> ~/.bashrc \
&& nix-env -iA nixpkgs.nixUnstable \
&& sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
`

2021-09-17 21:34 UTC, ghuntley commented
@shism2 see also https://www.github.com/gitpod-io/template-nix :)

2021-09-17 21:57 UTC, shism2 commented
@ghuntley Reason I attached was to show how to skip using workspace-base

2021-12-01 05:26 UTC, ghuntley commented
Adding in the main image instead #558

2021-12-01 05:26 UTC, closed without merging