Use GAR for image building and cache for push-main.yml workflow
gitpod-io/workspace-images pull request #718
Opened 2022-02-21 11:43 UTC by princerachit

## Description

Use GAR to build images instead of local registry. This would enable faster builds as GAR would house the previously built chunks.

## Related Issue(s)

Fixes partially https://github.com/gitpod-io/workspace-images/issues/713

## How to test

Can be only tested after merge.

## Release Notes

```release-note
None
```

## Documentation

2022-02-22 15:09 UTC, kylos101 requested changes
Hey @princerachit ,

How come GH action cache and the containerized docker registry are still present?
https://github.com/gitpod-io/workspace-images/pull/718/files#diff-2784b9c374ced1e3330a88b99fc29d7a5981296ecf89649161a9aaaf4ea5b25eR66-R78

Also, it looks like we're using the containized docker registry on port 5000 (in the main workflow, and the sync-containers file). Is that intentional?

2022-02-22 15:58 UTC, princerachit commented
Hey @kylos101 I am sorry, I believe I pushed a different ws commit. Let me find the right one.

2022-02-22 16:10 UTC, princerachit commented
Could not find the ws. Ended up making changes again as they were trivial.
Additionally, thanks for pointing out `localhost:5000` in the sync-containers.yml. I have renamed it so it is not misleading anymore.

2022-02-22 19:47 UTC, kylos101 commented on .github/workflows/push-main.yml
> +          sudo skopeo login -u ${{ env.docker_user }} --password=${{ env.docker_password }} https://${{ env.DH_IMAGE_REGISTRY }}
Why was the login for Docker Hub moved up to here? Ideally, this would not be done, like if a prior step fails.

2022-02-22 22:44 UTC, kylos101 commented on .github/workflows/push-main.yml
> +          sudo skopeo login -u ${{ env.docker_user }} --password=${{ env.docker_password }} https://${{ env.DH_IMAGE_REGISTRY }}
[force-pushed](https://github.com/gitpod-io/workspace-images/compare/0fa3a34529477a37edfd9657599a52442dc04f0b..0d45b7c3f50a76fc3bd304298906131c77773c86) the prs/gar-cache branch from [0fa3a34 ](https://github.com/gitpod-io/workspace-images/commit/0fa3a34529477a37edfd9657599a52442dc04f0b)to [0d45b7c ](https://github.com/gitpod-io/workspace-images/commit/0d45b7c3f50a76fc3bd304298906131c77773c86)[now](https://github.com/gitpod-io/workspace-images/pull/718#event-6121426267) to fix

2022-02-23 00:39 UTC, kylos101 approved these changes
LGTM

2022-02-23 00:40 UTC, merged