Add nix image
gitpod-io/workspace-images pull request #795
Opened 2022-04-04 16:11 UTC by emilytrau

## Description

Adds a minimal image variant with only the nix tool. This is useful for projects that leverage nix entirely for dependency management.

## How to test

n/a

## Release Notes

```release-note
Add new nix image
```

## Documentation

n/a

2022-04-04 23:54 UTC, utam0k approved these changes
Thanks for your contribution!

2022-04-04 23:55 UTC, utam0k commented
@princerachit I wonder why it doesn't include yet. Do you know some reasons?

2022-04-05 07:08 UTC, princerachit commented
hey @emilytrau I am not aware how widely nix is used by our users. Do we have this as a request from user or just something you think is useful.

I am asking these questions because nix is already shipped with `workspace-full` which is cached on our nodes and starts pretty fast.


@utam0k we did not have this because we initially targeted on having existing images migrated and then add new images based on user request

2022-04-05 07:47 UTC, emilytrau commented
@princerachit In projects where nix is the only base dependency it doesn't make sense to bring the rest of the language runtimes as well. Even just speaking for myself I would have a lot of use for this to reduce workspace startup time.

2022-04-05 08:08 UTC, Furisto commented
#792 is a similar request. We could add an image which only contains the base image and package managers.

2022-04-06 14:09 UTC, Furisto commented
Hey @emilytrau, I updated this PR to also include the brew chunk. That way we have an image which users can use as a base with their preferred package manager.

2022-04-06 17:05 UTC, kylos101 requested changes
Hi @emilytrau :wave: , 

Could you change the [combination name](https://github.com/gitpod-io/workspace-images/pull/795/files#diff-b8b5d73ca5ee13982e492c43c0198eda34749eab5c1f8b3621f6512ec5af6f8bR8) from `pkg` to `nix`?

Also, may we ask for your help with a couple things, so that this can be included with our CI/CD?
   * There are a couple spots in our CI that need to have this added added [[1](https://github.com/gitpod-io/workspace-images/blob/fb61836cd6673a54861de621d41154a781b530c6/.github/promote-images.yml#L21)][[2](https://github.com/gitpod-io/workspace-images/blob/fb61836cd6673a54861de621d41154a781b530c6/.github/sync-containers.yml#L18)]

Thank you so much! :pray:

2022-04-06 17:26 UTC, emilytrau commented
> Hey @emilytrau, I updated this PR to also include the brew chunk. That way we have an image which users can use as a base with their preferred package manager.

Hey @Furisto. In this case I see this image targetting use in nix-language projects, rather than as a toolkit of the package managers. This is similar to the other language-specific images. FYI Brew adds 700MB/30% to the total size. 

![IMG_0033](https://user-images.githubusercontent.com/13267947/162031629-b80efcd7-b611-444f-870e-d59cc713c2eb.jpeg)

2022-04-08 02:24 UTC, kylos101 approved these changes
Thanks for the contribution @emilytrau ! I agree, keeping `nix` by itself is the right call, especially for folks like a language.

2022-04-08 02:24 UTC, merged