feat: add chrome to full
gitpod-io/workspace-images pull request #903
Opened 2022-08-04 03:20 UTC by gengjiawen

## Description

I feel really unconveninent without it in full image. I checked the size, it's only around 130m increase.
It should be in full in the long run.

context: https://github.com/gitpod-io/workspace-images/pull/471/commits/5cfffd539ff4c60d8c53eca8e4b6835b4073a50f#r937310566

## Related Issue(s)

Fixes #

## How to test

## Release Notes

```release-note
```

## Documentation

2022-08-04 05:14 UTC, jenting approved these changes
LGTM

2022-08-04 08:42 UTC, axonasif commented
Hi @gengjiawen, just curious, whats the usecase? Headless chrome? Puppeteer?

Another thing, we're also installing and configuring chrome on the [`tool-vnc` chunk](https://github.com/gitpod-io/workspace-images/blob/1ad468e8452aa8a9c14ab5ba4cab10d4f4bb1c90/chunks/tool-vnc/Dockerfile#L10). I think it would be beneficial to decouple it from there into `tool-chrome` and add `tool-chrome` as a chunk under the `tool-vnc` combination. Would probably reduce the dazzle build time a lot.

2022-08-04 08:50 UTC, gengjiawen commented
> Hi @gengjiawen, just curious, whats the usecase? Headless chrome? Puppeteer?

Mostly frontend e2e testing like cypress and Puppeteer. Recently wasm (wasm-bindgen pretty lame on testing).
Another usecase is that ebook generating, in my case, gitbook.

2022-08-04 15:31 UTC, axonasif commented
Thanks for taking the step forward for the new change, but I think it's not exactly what I was talking about. Perhaps my message was a bit unclear, will try to collaborate with you on this one 🙏

2022-08-05 03:02 UTC, gengjiawen commented
> I think it would be beneficial to decouple it from there into `tool-chrome` and add `tool-chrome` as a chunk for the `tool-vnc` combination.

You mean this part ?

2022-08-09 06:12 UTC, gengjiawen commented
ping @axonasif

2022-08-16 08:07 UTC, axonasif commented
Hey @gengjiawen, thanks a lot for your patience, could you please toggle on [`Allow edits from maintainers`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on your PR right-side-bar? I want to push some commits into your branch.

2022-08-16 08:21 UTC, gengjiawen commented
> Hey @gengjiawen, thanks a lot for your patience, could you please toggle on [`Allow edits from maintainers`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on your PR right-side-bar? I want to push some commits into your branch.

I already checked last week. Maybe something wrong on your side ?
<img width="350" alt="image" src="https://user-images.githubusercontent.com/3759816/184832863-6559ee26-4c89-43d7-8643-a7dffb29428f.png">

2022-08-16 08:33 UTC, atduarte commented
Thank you for the contribution @gengjiawen! 🎉 

Could you share a bit more about why you think this should be included? 🙏  I'm concerned that the full image is already very big and that not a lot of users would actually use it.

2022-08-16 08:43 UTC, gengjiawen commented
> Thank you for the contribution @gengjiawen! 🎉
> 
> Could you share a bit more about why you think this should be included? 🙏 I'm concerned that the full image is already very big and that not a lot of users would actually use it.

I update pr description with more info.

2022-08-16 09:55 UTC, axonasif commented
> > Hey @gengjiawen, thanks a lot for your patience, could you please toggle on [`Allow edits from maintainers`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on your PR right-side-bar? I want to push some commits into your branch.
> 
> I already checked last week. Maybe something wrong on your side ? <img alt="image" width="350" src="https://user-images.githubusercontent.com/3759816/184832863-6559ee26-4c89-43d7-8643-a7dffb29428f.png">

my https://gitpod.io/integrations>github was somehow reset, weird 😅 
commits are pushed now.

2022-08-17 09:44 UTC, gengjiawen commented
@axonasif CI passed. Can you merge this ? thx.

2022-08-17 09:58 UTC, atduarte commented
@gengjiawen as also mentioned previously by @kylos101 [[1](https://github.com/gitpod-io/workspace-images/pull/471#discussion_r802202019)], we are not convinced that workspace-full should also contain chrome given it's size.

2022-08-17 10:03 UTC, atduarte requested changes
@gengjiawen as also mentioned previously by @kylos101 [https://github.com/gitpod-io/workspace-images/pull/471#discussion_r802202019], we are not convinced that workspace-full should also contain chrome given it's size.

2022-08-17 10:03 UTC, atduarte commented on dazzle.yaml
> +        - tool-chrome
```suggestion
```

2022-08-17 11:56 UTC, gengjiawen commented
> @gengjiawen as also mentioned previously by @kylos101 [[1](https://github.com/gitpod-io/workspace-images/pull/471#discussion_r802202019)], we are not convinced that workspace-full should also contain chrome given it's size.

I think it's a balance, and it's worth it. With all due respect It's much more useful and make basic function out of the box.
It's just make gitpod more `intuitive`. 

And for size, in my humble experience, this is more deserve it in full than closure or nginx.

2022-08-17 12:40 UTC, atduarte commented
I understand your point of view. Currently we are very wary of increasing the size of the image and do so only if _really_ needed as it negatively impacts workspace startup times for all, and we can't really remove langs/tools later as we risk breaking users' workspaces.

The image is already at 7.1GB, chrome would actually add 648MB to it. 😥 

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/666176/185127369-10347923-eef2-4df1-943f-8afa376b4964.png">

2022-08-17 13:14 UTC, axonasif commented
Hey @gengjiawen, since our workspace team suggests that we may not add chrome to the full image, you could utilize the [dotfiles](https://www.gitpod.io/docs/config-dotfiles) feature 🚀 

In your dotfiles `install.sh`, you could have this (I basically copy pasted from the chrome dockerfile):
```bash
#!/usr/bin/env bash

(
    cd /tmp && glink="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" \
	    && wget -q "$glink" \
	    && sudo install-packages libasound2-dev libgtk-3-dev libnss3-dev \
	    fonts-noto fonts-noto-cjk ./"${glink##*/}" \
	    && ln -srf /usr/bin/google-chrome /usr/bin/chromium \
	    && t="$HOME/.config/google-chrome/First Run" && sudo -u gitpod mkdir -p "${t%/*}" && sudo -u gitpod touch "$t" \
	    && t="/etc/opt/chrome/policies/managed/managed_policies.json" && mkdir -p "${t%/*}" && printf '{ "%s": %s }\n' DefaultBrowserSettingEnabled false > "$t"
) & disown

echo "export QTWEBENGINE_DISABLE_SANDBOX=1" >> $HOME/.bashrc
```

This will install chrome for each of your personal workspaces 😄

2022-08-19 06:33 UTC, gengjiawen commented
> I understand your point of view. Currently we are very wary of increasing the size of the image and do so only if _really_ needed as it negatively impacts workspace startup times for all, and we can't really remove langs/tools later as we risk breaking users' workspaces.
> 
> The image is already at 7.1GB, chrome would actually add 648MB to it. 😥
> 
> <img alt="image" width="1144" src="https://user-images.githubusercontent.com/666176/185127369-10347923-eef2-4df1-943f-8afa376b4964.png">

Thx for this detailed info, I take a bit of more into this, looks like chrome is only 300mb, the other is mainly gtk (electron likely to use, this can keep only in vnc)

Is 300mb acceptable for full ?

2022-09-16 06:22 UTC, gengjiawen commented
@axonasif I removed chrome from full, I think it is still worth it in tool-vnc.

2022-09-16 16:30 UTC, axonasif approved these changes

2022-09-22 06:29 UTC, gengjiawen commented
@axonasif Can you merge this ?

2022-09-22 12:55 UTC, atduarte approved these changes

2022-09-22 12:55 UTC, atduarte commented
Changed the title to be more inline with what the code is now doing. Does it make sense to you?

2022-09-22 13:28 UTC, gengjiawen commented
> Changed the title to be more inline with what the code is now doing. Does it make sense to you?

More like “Refactor install chrome on vnc”

2022-09-22 14:36 UTC, meysholdt commented
hi @gengjiawen and thank you for this and all you past contributions! We just noticed that we don't have a singed CLA from you on file yet. Would you mind signing this CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [moritz@gitpod.io](mailto:moritz@gitpod.io).

2022-09-23 02:58 UTC, gengjiawen commented
> hi @gengjiawen and thank you for this and all you past contributions! We just noticed that we don't have a singed CLA from you on file yet. Would you mind signing this CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [moritz@gitpod.io](mailto:moritz@gitpod.io).

done. But the process is so verbose. I hope you can adopt solution like facebook cla or google cla, which is clean and fast.

2022-09-26 02:51 UTC, gengjiawen commented
Can anyone merge this ? thx.

2022-09-26 08:54 UTC, merged

2022-10-05 17:52 UTC, kylos101 commented
:wave: @gengjiawen @axonasif  this should be live now :smile: