feat: add linuxbrew completion support for bash
gitpod-io/workspace-images pull request #943
Opened 2022-10-07 21:16 UTC by shyim

2022-10-11 04:51 UTC, jenting commented
CI failed. Could you please check it?
Thank you.

2022-10-11 07:40 UTC, shyim commented
@jenting Is it fine if I disable that shellcheck's? (like in python) I would not like to modify the original code from Homebrew :sweat_smile:

2022-10-12 06:25 UTC, jenting reviewed
Reference to https://github.com/gitpod-io/workspace-images/blob/main/chunks/lang-node/nvm-lazy.sh#L21

2022-10-12 06:25 UTC, jenting commented on chunks/tool-brew/completion-hook.bash
> +    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
You could add
```shell
# shellcheck disable=SC1091
```

2022-10-12 06:25 UTC, jenting commented on chunks/tool-brew/completion-hook.bash
> +      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
You could add
```shell
# shellcheck disable=SC1090
```

2022-10-16 17:52 UTC, axonasif commented on chunks/tool-brew/completion-hook.bash
> +fi
There is no need to implement custom logic.
Use `homebrew`'s shellenv instead.

```suggestion
#!/usr/bin/env bash

homebrew_bin="/home/linuxbrew/bin/brew"

if test -x "$homebrew_bin"; then {
    eval "$("$homebrew_bin" shellenv)"
} fi

unset homebrew_bin
```

2022-10-16 17:55 UTC, axonasif requested changes
It's better to use the builtin `shellenv` of `brew` that loads completions and even more instead of implementing it ourselves. Also, please rename `completion-hook.bash` to something like `homebrew.bash` and update the path on your `Dockerfile` afterwards.

2022-10-16 18:11 UTC, shyim commented
@axonasif `/home/linuxbrew/.linuxbrew/bin/brew shellenv` does nothing.

It prints nothing out. Are you sure? :D

2022-10-16 18:13 UTC, shyim commented
AHHH you are talking about completion support for homebrew self.

I am talking about installed Software using homebrew 😂

2022-10-16 18:17 UTC, axonasif commented
> AHHH you are talking about completion support for homebrew self.
> 
> I am talking about installed Software using homebrew 😂

I'm not, please check yourself.

2022-10-16 18:18 UTC, axonasif commented
> @axonasif `/home/linuxbrew/.linuxbrew/bin/brew shellenv` does nothing.
> 
> It prints nothing out. Are you sure? :D

It's not supposed to print out anything if the necessary variables are already set.

2022-10-16 18:24 UTC, shyim commented
Never mind it works already without my changes. I was drunken or so. I have no idea.

2022-10-16 18:24 UTC, closed without merging

2022-10-16 18:30 UTC, axonasif commented
> Never mind it works already without my changes. I was drunken or so. I have no idea.
> 
> Sorry 😢

Don't be sorry 😅 . Your changes are [valid](https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash).

However, we're already using `bash-completion` package that is loaded beforehand, which is why it works without the change. Loading it from homebrew again might not be useful for most well-known packages.

2022-10-16 18:37 UTC, shyim commented
yea i guess.

The real issue was that I just have to reopen the bash

```bash
brew install FriendsOfShopware/tap/shopware-cli
shopware-cli <tab> does not work
```

reopen a terminal

```
shopware-cli <tab> works now
```