bump `node-lts` to 18 & `node-current` to 19
gitpod-io/workspace-images pull request #966
Opened 2022-10-26 19:05 UTC by Siddhant-K-code

## Description
Node LTS is on Version 18 (check [here](https://nodejs.org/))

## Release Notes

```release-note
breaking: Node-LTS to `v18.12.0` (from Node-LTS `v16.18.0`) & Node-Current to `v19.0.0` (from Node-Current `v18.12.0`)
```

## Documentation

This should go with https://github.com/gitpod-io/website/pull/2883

2022-10-26 23:05 UTC, sagor999 commented
@gitpod-io/engineering-ide @gitpod-io/engineering-webapp any concerns with bumping node from v16 to v18 by default?

2022-10-27 07:17 UTC, geropl commented
@sagor999 LGTM, we're pinning it [here](https://github.com/gitpod-io/gitpod/blob/3393f87cd07b10b13d4298c20d5f8abf894f06be/dev/image/Dockerfile#L133-L138).

2022-10-27 07:44 UTC, akosyakov commented
> any concerns with bumping node from v16 to v18 by default?

breaking users, we should communicate it well through our channels with a strategy how to pin

2022-10-27 08:06 UTC, filiptronicek commented
We could add a section like "upcoming changes to workspace images" to the changelog to give a date and guidance for pinning like Anton mentioned. Maybe just breaking on users without prior notice isn't ideal here. @Siddhant-K-code

2022-10-27 09:10 UTC, atduarte commented
Related with two ongoing internal RFCs:
- [Workspace Images - Pinned Language Versions ](https://www.notion.so/gitpod/Workspace-Images-Pinned-Language-Versions-9d9483fb3dda409889d4fe0aea8b0a88)
- [Workspace Images - Release Channels](https://www.notion.so/gitpod/Workspace-Images-Release-Channels-4234c06f69cd4c9692603938a3d8a0ff)

2022-11-24 03:44 UTC, gengjiawen commented
> > any concerns with bumping node from v16 to v18 by default?
> 
> breaking users, we should communicate it well through our channels with a strategy how to pin

TBH,  user should keep their app compatible with latest LTS or they should lock their Node.js version.
Gitpod should focus on deliver LTS with latest security fix and features. Currently default to 18 is the right thing todo.

2022-12-20 03:54 UTC, Siddhant-K-code commented
Is there any plans to bump `node-lts` version further with a warning ⚠️ in changelogs (due for 2 last months)?

Or we can simply close this PR 😃

2023-01-28 16:14 UTC, Siddhant-K-code commented
Related https://github.com/gitpod-io/gitpod/issues/16072

2023-01-29 01:29 UTC, gengjiawen commented
> > > any concerns with bumping node from v16 to v18 by default?
> > 
> > 
> > breaking users, we should communicate it well through our channels with a strategy how to pin
> 
> TBH, user should keep their app compatible with latest LTS or they should lock their Node.js version. Gitpod should focus on deliver LTS with latest security fix and features. Currently default to 18 is the right thing todo.

@atduarte @akosyakov Anything to push this forward ?

Also, for the breaking users. Actually they can lock their node versions, since gitpod also provide nvm.

2023-02-01 09:03 UTC, akosyakov commented
I agree that our base should be LTS in this case. Node users are quite adaptive. My original comment was that it should be a part of Changelog.

In long term we should have a process which makes it clear for users via docs and changelog, and if possible executed automatically.

2023-02-01 09:04 UTC, akosyakov commented
@loujaybee maybe we should do @filiptronicek suggestion for this changelog: https://github.com/gitpod-io/workspace-images/pull/966#issuecomment-1293147489 too late?

2023-02-13 06:18 UTC, gengjiawen commented
This became drawbacks since many project requires node 18, especially related to chatgpt tools.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'chatgpt@3.5.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```

2023-02-13 06:21 UTC, Siddhant-K-code commented
We would gonna update this on 28th Feb ([announcement in changelog](https://www.gitpod.io/changelog/january-changelog#workspace-images-os-and-node-versions-update)). Till then you could follow [this guide](https://www.gitpod.io/docs/introduction/languages/javascript#updating-node-versions) (by using `nvm`)

2023-03-02 22:22 UTC, kylos101 approved these changes
Dear @Siddhant-K-code ,

You are a gentleman and a scholar, thank you so much!

This will ship next week as latest. 

This should also ship tomorrow, or Monday at the latest, as a timestamped tag.

2023-03-02 22:25 UTC, kylos101 requested changes
@Siddhant-K-code could I ask you to accept the suggested changes? I can merge after.

Alternatively, we can close this PR in favor of https://github.com/gitpod-io/workspace-images/pull/1017/commits/acbb0bcae61310414c4ae54f66ce7c2df492e793.

Let me know your preference?

2023-03-02 22:25 UTC, kylos101 commented on chunks/lang-node/chunk.yaml
> +      NODE_VERSION: 19.0.0
```suggestion
      NODE_VERSION: 19.17.0
```

2023-03-02 22:25 UTC, kylos101 commented on chunks/lang-node/chunk.yaml
>        NODE_VERSION: 18.13.0
```suggestion
      NODE_VERSION: 18.14.2
```

2023-03-03 02:24 UTC, Siddhant-K-code commented
> Alternatively, we can close this PR in favor of https://github.com/gitpod-io/workspace-images/commit/acbb0bcae61310414c4ae54f66ce7c2df492e793.

yeah, this makes more sense to release all at once. Closing this PR 🙏🏽 

Thanks ✨

2023-03-03 02:24 UTC, closed without merging